### ISSUE TITLE
Themes don't load

### ISSUE THREAD

**Issue by purukaushik** [owainlewis/emacs-color-themes#32]
Tried MELPA -> error downloading 
Tried install.sh and updating init.el -> no luck either.

Version:
GNU Emacs 24.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.10.7) of 2014-03-07 on lamiak, modified by Debian

**Comment by trashofmasters** [comment]
Hi, 

Please make sure you're pointing Emacs to your theme directory with:

```elisp
(add-to-list 'custom-theme-load-path "/path/to/emacs-color-themes")
```

Once that's evaluated you should be able to select them with `M-x load-theme`.

**Comment by trashofmasters** [comment]
@purukaushik did you have any luck installing the themes manually?

If you want to give MELPA another try, use `M-x package-refresh-contents` before installing the theme package with `M-x package-install`. In my experience this solves 90% of the packages **not found** errors.

Good luck.

**Comment by purukaushik** [comment]
Thanks. the refresh contents worked. :)
